spring.application.name=McqExamApp
server.port=8081

# Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/mcqexamdb
spring.datasource.username=postgres

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# JWT

jwt.access-token-expiration-ms=3600000
jwt.refresh-token-expiration-ms=2592000000

#logging
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG



#app.oauth2.redirect-uri=mcqexamapp://oauth2redirect
# Resend (email OTP for password reset)

resend.from-email=onboarding@resend.dev
